// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCTIVEBuilder(
		myfirstmodule.proxies.FACTA _fACTA_3,
		myfirstmodule.proxies.FACTA _fACTA_2,
		myfirstmodule.proxies.holderdetails _holderdetails_2,
		myfirstmodule.proxies.nominations _nominations_2,
		myfirstmodule.proxies.adressdetails _adressdetails_2,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.bankdetails _bankdetails_2,
		myfirstmodule.proxies.clientdetails _clientdetails_2,
		myfirstmodule.proxies.basicdetails _basicdetails_2,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACTIVE");
		builder = builder.withParam("FACTA_3", _fACTA_3);
		builder = builder.withParam("FACTA_2", _fACTA_2);
		builder = builder.withParam("holderdetails_2", _holderdetails_2);
		builder = builder.withParam("nominations_2", _nominations_2);
		builder = builder.withParam("adressdetails_2", _adressdetails_2);
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("bankdetails_2", _bankdetails_2);
		builder = builder.withParam("clientdetails_2", _clientdetails_2);
		builder = builder.withParam("basicdetails_2", _basicdetails_2);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		return builder;
	}

	public static void aCTIVE(
		IContext context,
		myfirstmodule.proxies.FACTA _fACTA_3,
		myfirstmodule.proxies.FACTA _fACTA_2,
		myfirstmodule.proxies.holderdetails _holderdetails_2,
		myfirstmodule.proxies.nominations _nominations_2,
		myfirstmodule.proxies.adressdetails _adressdetails_2,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.bankdetails _bankdetails_2,
		myfirstmodule.proxies.clientdetails _clientdetails_2,
		myfirstmodule.proxies.basicdetails _basicdetails_2,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		aCTIVEBuilder(
				_fACTA_3,
				_fACTA_2,
				_holderdetails_2,
				_nominations_2,
				_adressdetails_2,
				_depository1,
				_bankdetails_2,
				_clientdetails_2,
				_basicdetails_2,
				_nominations,
				_holderdetails,
				_draft,
				_bankdetails,
				_adressdetails,
				_uploaddocument,
				_fACTA,
				_fileDocument,
				_clientdetails,
				_basicdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aPPROVALBuilder(
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.APPROVAL");
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		return builder;
	}

	public static void aPPROVAL(
		IContext context,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails
	)
	{
		aPPROVALBuilder(
				_depository1,
				_uploaddocument,
				_draft,
				_holderdetails,
				_clientdetails,
				_basicdetails,
				_fileDocument,
				_fACTA,
				_nominations,
				_bankdetails,
				_adressdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aUTHENTICATEBuilder(
		myfirstmodule.proxies.FACTA _fACTA_3,
		myfirstmodule.proxies.FACTA _fACTA_2,
		myfirstmodule.proxies.holderdetails _holderdetails_2,
		myfirstmodule.proxies.nominations _nominations_2,
		myfirstmodule.proxies.adressdetails _adressdetails_2,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.bankdetails _bankdetails_2,
		myfirstmodule.proxies.clientdetails _clientdetails_2,
		myfirstmodule.proxies.basicdetails _basicdetails_2,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.draft _draft_2
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.AUTHENTICATE");
		builder = builder.withParam("FACTA_3", _fACTA_3);
		builder = builder.withParam("FACTA_2", _fACTA_2);
		builder = builder.withParam("holderdetails_2", _holderdetails_2);
		builder = builder.withParam("nominations_2", _nominations_2);
		builder = builder.withParam("adressdetails_2", _adressdetails_2);
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("bankdetails_2", _bankdetails_2);
		builder = builder.withParam("clientdetails_2", _clientdetails_2);
		builder = builder.withParam("basicdetails_2", _basicdetails_2);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("draft_2", _draft_2);
		return builder;
	}

	public static void aUTHENTICATE(
		IContext context,
		myfirstmodule.proxies.FACTA _fACTA_3,
		myfirstmodule.proxies.FACTA _fACTA_2,
		myfirstmodule.proxies.holderdetails _holderdetails_2,
		myfirstmodule.proxies.nominations _nominations_2,
		myfirstmodule.proxies.adressdetails _adressdetails_2,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.bankdetails _bankdetails_2,
		myfirstmodule.proxies.clientdetails _clientdetails_2,
		myfirstmodule.proxies.basicdetails _basicdetails_2,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.draft _draft_2
	)
	{
		aUTHENTICATEBuilder(
				_fACTA_3,
				_fACTA_2,
				_holderdetails_2,
				_nominations_2,
				_adressdetails_2,
				_depository1,
				_bankdetails_2,
				_clientdetails_2,
				_basicdetails_2,
				_nominations,
				_holderdetails,
				_draft,
				_bankdetails,
				_adressdetails,
				_uploaddocument,
				_fACTA,
				_fileDocument,
				_clientdetails,
				_basicdetails,
				_draft_2
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aUTHENTICATE_OR_NOTBuilder(
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.draft _draft_1,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.AUTHENTICATE_OR_NOT");
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("draft_1", _draft_1);
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		return builder;
	}

	public static void aUTHENTICATE_OR_NOT(
		IContext context,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.draft _draft_1,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		aUTHENTICATE_OR_NOTBuilder(
				_draft,
				_draft_1,
				_depository1,
				_fileDocument,
				_uploaddocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder eDITDRAFTS_MICROBuilder(
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.EDITDRAFTS_MICRO");
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		return builder;
	}

	public static void eDITDRAFTS_MICRO(
		IContext context,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		eDITDRAFTS_MICROBuilder(
				_draft,
				_depository1,
				_fileDocument,
				_uploaddocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder isactiveBuilder(
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.isactive");
		builder = builder.withParam("basicdetails", _basicdetails);
		return builder;
	}

	public static void isactive(
		IContext context,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		isactiveBuilder(
				_basicdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mAKE_ACTIVEBuilder(
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.draft _draft_1,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MAKE_ACTIVE");
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("draft_1", _draft_1);
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		return builder;
	}

	public static void mAKE_ACTIVE(
		IContext context,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.draft _draft_1,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		mAKE_ACTIVEBuilder(
				_draft,
				_draft_1,
				_depository1,
				_fileDocument,
				_uploaddocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sAVEDRAFT_MICROBuilder(
		myfirstmodule.proxies.clientdetails _clientdetails,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.SAVEDRAFT_MICRO");
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		return builder;
	}

	public static void sAVEDRAFT_MICRO(
		IContext context,
		myfirstmodule.proxies.clientdetails _clientdetails,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails
	)
	{
		sAVEDRAFT_MICROBuilder(
				_clientdetails,
				_fileDocument,
				_nominations,
				_fACTA,
				_adressdetails,
				_bankdetails,
				_basicdetails,
				_holderdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sHOW_UCCLISTBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.SHOW_UCCLIST");
		return builder;
	}

	public static void sHOW_UCCLIST(IContext context)
	{
		sHOW_UCCLISTBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sHOW_VERIFY_OR_NOTBuilder(
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.SHOW_VERIFY_OR_NOT");
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		return builder;
	}

	public static void sHOW_VERIFY_OR_NOT(
		IContext context,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		sHOW_VERIFY_OR_NOTBuilder(
				_draft,
				_depository1,
				_fileDocument,
				_uploaddocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showactivepageBuilder(
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showactivepage");
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		return builder;
	}

	public static void showactivepage(
		IContext context,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		showactivepageBuilder(
				_depository1,
				_draft,
				_uploaddocument,
				_fACTA,
				_fileDocument,
				_nominations,
				_adressdetails,
				_bankdetails,
				_holderdetails,
				_clientdetails,
				_basicdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sHOWAPROVE_OR_NOTBuilder(
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.SHOWAPROVE_OR_NOT");
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		return builder;
	}

	public static void sHOWAPROVE_OR_NOT(
		IContext context,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.depository1 _depository1,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.Uploaddocument _uploaddocument
	)
	{
		sHOWAPROVE_OR_NOTBuilder(
				_draft,
				_depository1,
				_fileDocument,
				_uploaddocument
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showform1Builder(
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showform1");
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void showform1(
		IContext context,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		showform1Builder(
				_basicdetails,
				_clientdetails,
				_holderdetails,
				_bankdetails,
				_adressdetails,
				_fACTA,
				_nominations,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showform2Builder(
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showform2");
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void showform2(
		IContext context,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		showform2Builder(
				_basicdetails,
				_clientdetails,
				_holderdetails,
				_bankdetails,
				_adressdetails,
				_fACTA,
				_nominations,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showform3Builder(
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showform3");
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void showform3(
		IContext context,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		showform3Builder(
				_basicdetails,
				_holderdetails,
				_clientdetails,
				_bankdetails,
				_adressdetails,
				_fACTA,
				_nominations,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showform5Builder(
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showform5");
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void showform5(
		IContext context,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		showform5Builder(
				_bankdetails,
				_basicdetails,
				_clientdetails,
				_holderdetails,
				_adressdetails,
				_fACTA,
				_nominations,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showform6Builder(
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showform6");
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void showform6(
		IContext context,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		showform6Builder(
				_adressdetails,
				_basicdetails,
				_holderdetails,
				_clientdetails,
				_bankdetails,
				_fACTA,
				_nominations,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showform7Builder(
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showform7");
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void showform7(
		IContext context,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		showform7Builder(
				_nominations,
				_fACTA,
				_adressdetails,
				_bankdetails,
				_clientdetails,
				_holderdetails,
				_basicdetails,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sHOWPAGESBuilder(
		myfirstmodule.proxies.draft _draft,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.SHOWPAGES");
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void sHOWPAGES(
		IContext context,
		myfirstmodule.proxies.draft _draft,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		sHOWPAGESBuilder(
				_draft,
				_fileDocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showPending_To_verifyBuilder(
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ShowPending_To_verify");
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		return builder;
	}

	public static void showPending_To_verify(
		IContext context,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		showPending_To_verifyBuilder(
				_depository1,
				_draft,
				_uploaddocument,
				_fACTA,
				_fileDocument,
				_nominations,
				_adressdetails,
				_bankdetails,
				_holderdetails,
				_clientdetails,
				_basicdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showPendingApprovalPAGEBuilder(
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showPendingApprovalPAGE");
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		return builder;
	}

	public static void showPendingApprovalPAGE(
		IContext context,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		showPendingApprovalPAGEBuilder(
				_depository1,
				_draft,
				_uploaddocument,
				_fACTA,
				_fileDocument,
				_nominations,
				_adressdetails,
				_bankdetails,
				_holderdetails,
				_clientdetails,
				_basicdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder showPendingtoAuthenticateBuilder(
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.showPendingtoAuthenticate");
		builder = builder.withParam("depository1", _depository1);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		return builder;
	}

	public static void showPendingtoAuthenticate(
		IContext context,
		myfirstmodule.proxies.depository1 _depository1,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.basicdetails _basicdetails
	)
	{
		showPendingtoAuthenticateBuilder(
				_depository1,
				_draft,
				_uploaddocument,
				_fACTA,
				_fileDocument,
				_nominations,
				_adressdetails,
				_bankdetails,
				_holderdetails,
				_clientdetails,
				_basicdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder step1validBuilder(
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.step1valid");
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void step1valid(
		IContext context,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		step1validBuilder(
				_basicdetails,
				_clientdetails,
				_holderdetails,
				_bankdetails,
				_adressdetails,
				_fACTA,
				_nominations,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder step2validBuilder(
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.step2valid");
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void step2valid(
		IContext context,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		step2validBuilder(
				_holderdetails,
				_basicdetails,
				_bankdetails,
				_adressdetails,
				_clientdetails,
				_fACTA,
				_nominations,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder step3validBuilder(
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.step3valid");
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void step3valid(
		IContext context,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		step3validBuilder(
				_bankdetails,
				_basicdetails,
				_clientdetails,
				_holderdetails,
				_adressdetails,
				_fACTA,
				_nominations,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder step5validBuilder(
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.draft _draft_1,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.step5valid");
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("draft_1", _draft_1);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void step5valid(
		IContext context,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.nominations _nominations,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.draft _draft_1,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		step5validBuilder(
				_adressdetails,
				_basicdetails,
				_holderdetails,
				_clientdetails,
				_bankdetails,
				_fACTA,
				_nominations,
				_fileDocument,
				_draft,
				_uploaddocument,
				_draft_1,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder step6validBuilder(
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		system.proxies.FileDocument _fileDocument_2,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.step6valid");
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("FileDocument_2", _fileDocument_2);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void step6valid(
		IContext context,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		system.proxies.FileDocument _fileDocument_2,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		step6validBuilder(
				_adressdetails,
				_bankdetails,
				_clientdetails,
				_holderdetails,
				_nominations,
				_basicdetails,
				_fACTA,
				_fileDocument,
				_fileDocument_2,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder step7validBuilder(
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.step7valid");
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("draft", _draft);
		builder = builder.withParam("Uploaddocument", _uploaddocument);
		builder = builder.withParam("depository1", _depository1);
		return builder;
	}

	public static void step7valid(
		IContext context,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.clientdetails _clientdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.FACTA _fACTA,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.draft _draft,
		myfirstmodule.proxies.Uploaddocument _uploaddocument,
		myfirstmodule.proxies.depository1 _depository1
	)
	{
		step7validBuilder(
				_adressdetails,
				_bankdetails,
				_basicdetails,
				_clientdetails,
				_holderdetails,
				_nominations,
				_fACTA,
				_fileDocument,
				_draft,
				_uploaddocument,
				_depository1
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder toUpperCase_MicroflowBuilder(
		myfirstmodule.proxies.holderdetails _holderdetails
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ToUpperCase_Microflow");
		builder = builder.withParam("holderdetails", _holderdetails);
		return builder;
	}

	public static void toUpperCase_Microflow(
		IContext context,
		myfirstmodule.proxies.holderdetails _holderdetails
	)
	{
		toUpperCase_MicroflowBuilder(
				_holderdetails
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vERIFY_FORMBuilder(
		myfirstmodule.proxies.clientdetails _clientdetails,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.draft _draft
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.VERIFY_FORM");
		builder = builder.withParam("clientdetails", _clientdetails);
		builder = builder.withParam("FileDocument", _fileDocument);
		builder = builder.withParam("nominations", _nominations);
		builder = builder.withParam("FACTA", _fACTA);
		builder = builder.withParam("adressdetails", _adressdetails);
		builder = builder.withParam("bankdetails", _bankdetails);
		builder = builder.withParam("basicdetails", _basicdetails);
		builder = builder.withParam("holderdetails", _holderdetails);
		builder = builder.withParam("draft", _draft);
		return builder;
	}

	public static void vERIFY_FORM(
		IContext context,
		myfirstmodule.proxies.clientdetails _clientdetails,
		system.proxies.FileDocument _fileDocument,
		myfirstmodule.proxies.nominations _nominations,
		myfirstmodule.proxies.FACTA _fACTA,
		myfirstmodule.proxies.adressdetails _adressdetails,
		myfirstmodule.proxies.bankdetails _bankdetails,
		myfirstmodule.proxies.basicdetails _basicdetails,
		myfirstmodule.proxies.holderdetails _holderdetails,
		myfirstmodule.proxies.draft _draft
	)
	{
		vERIFY_FORMBuilder(
				_clientdetails,
				_fileDocument,
				_nominations,
				_fACTA,
				_adressdetails,
				_bankdetails,
				_basicdetails,
				_holderdetails,
				_draft
			)
			.execute(context);
	}
}
