// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum Adresstype2
{
	residenceorbusiness(new java.lang.String[][] { new java.lang.String[] { "en_US", "residenceorbusiness" } }),
	residence(new java.lang.String[][] { new java.lang.String[] { "en_US", "residence" } }),
	business(new java.lang.String[][] { new java.lang.String[] { "en_US", "business" } }),
	residence_or_business_foreign(new java.lang.String[][] { new java.lang.String[] { "en_US", "residence or business foreign" } }),
	residence_foriegn(new java.lang.String[][] { new java.lang.String[] { "en_US", "residence foriegn" } }),
	business_foriegn(new java.lang.String[][] { new java.lang.String[] { "en_US", "business foriegn" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Adresstype2(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
