// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class bankdetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bankdetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.bankdetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		pupose("pupose"),
		accounttype("accounttype"),
		accountno("accountno"),
		bankname("bankname"),
		branchname("branchname"),
		ifsc("ifsc"),
		bankcity("bankcity"),
		step3completed("step3completed"),
		dataid("dataid");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public bankdetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected bankdetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bankdetailsMendixObject)
	{
		if (bankdetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, bankdetailsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.bankdetailsMendixObject = bankdetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.bankdetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.bankdetails(context, mendixObject);
	}

	public static myfirstmodule.proxies.bankdetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.bankdetails.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.bankdetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.bankdetails.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of pupose
	 * @param pupose
	 */
	public final myfirstmodule.proxies.pupose getpupose()
	{
		return getpupose(getContext());
	}

	/**
	 * @param context
	 * @return value of pupose
	 */
	public final myfirstmodule.proxies.pupose getpupose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.pupose.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.pupose.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of pupose
	 * @param pupose
	 */
	public final void setpupose(myfirstmodule.proxies.pupose pupose)
	{
		setpupose(getContext(), pupose);
	}

	/**
	 * Set value of pupose
	 * @param context
	 * @param pupose
	 */
	public final void setpupose(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.pupose pupose)
	{
		if (pupose != null) {
			getMendixObject().setValue(context, MemberNames.pupose.toString(), pupose.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.pupose.toString(), null);
		}
	}

	/**
	 * Get value of accounttype
	 * @param accounttype
	 */
	public final myfirstmodule.proxies.accounttype getaccounttype()
	{
		return getaccounttype(getContext());
	}

	/**
	 * @param context
	 * @return value of accounttype
	 */
	public final myfirstmodule.proxies.accounttype getaccounttype(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.accounttype.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.accounttype.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of accounttype
	 * @param accounttype
	 */
	public final void setaccounttype(myfirstmodule.proxies.accounttype accounttype)
	{
		setaccounttype(getContext(), accounttype);
	}

	/**
	 * Set value of accounttype
	 * @param context
	 * @param accounttype
	 */
	public final void setaccounttype(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.accounttype accounttype)
	{
		if (accounttype != null) {
			getMendixObject().setValue(context, MemberNames.accounttype.toString(), accounttype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.accounttype.toString(), null);
		}
	}

	/**
	 * @return value of accountno
	 */
	public final java.lang.String getaccountno()
	{
		return getaccountno(getContext());
	}

	/**
	 * @param context
	 * @return value of accountno
	 */
	public final java.lang.String getaccountno(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.accountno.toString());
	}

	/**
	 * Set value of accountno
	 * @param accountno
	 */
	public final void setaccountno(java.lang.String accountno)
	{
		setaccountno(getContext(), accountno);
	}

	/**
	 * Set value of accountno
	 * @param context
	 * @param accountno
	 */
	public final void setaccountno(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accountno)
	{
		getMendixObject().setValue(context, MemberNames.accountno.toString(), accountno);
	}

	/**
	 * @return value of bankname
	 */
	public final java.lang.String getbankname()
	{
		return getbankname(getContext());
	}

	/**
	 * @param context
	 * @return value of bankname
	 */
	public final java.lang.String getbankname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.bankname.toString());
	}

	/**
	 * Set value of bankname
	 * @param bankname
	 */
	public final void setbankname(java.lang.String bankname)
	{
		setbankname(getContext(), bankname);
	}

	/**
	 * Set value of bankname
	 * @param context
	 * @param bankname
	 */
	public final void setbankname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bankname)
	{
		getMendixObject().setValue(context, MemberNames.bankname.toString(), bankname);
	}

	/**
	 * @return value of branchname
	 */
	public final java.lang.String getbranchname()
	{
		return getbranchname(getContext());
	}

	/**
	 * @param context
	 * @return value of branchname
	 */
	public final java.lang.String getbranchname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.branchname.toString());
	}

	/**
	 * Set value of branchname
	 * @param branchname
	 */
	public final void setbranchname(java.lang.String branchname)
	{
		setbranchname(getContext(), branchname);
	}

	/**
	 * Set value of branchname
	 * @param context
	 * @param branchname
	 */
	public final void setbranchname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String branchname)
	{
		getMendixObject().setValue(context, MemberNames.branchname.toString(), branchname);
	}

	/**
	 * @return value of ifsc
	 */
	public final java.lang.String getifsc()
	{
		return getifsc(getContext());
	}

	/**
	 * @param context
	 * @return value of ifsc
	 */
	public final java.lang.String getifsc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ifsc.toString());
	}

	/**
	 * Set value of ifsc
	 * @param ifsc
	 */
	public final void setifsc(java.lang.String ifsc)
	{
		setifsc(getContext(), ifsc);
	}

	/**
	 * Set value of ifsc
	 * @param context
	 * @param ifsc
	 */
	public final void setifsc(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ifsc)
	{
		getMendixObject().setValue(context, MemberNames.ifsc.toString(), ifsc);
	}

	/**
	 * @return value of bankcity
	 */
	public final java.lang.String getbankcity()
	{
		return getbankcity(getContext());
	}

	/**
	 * @param context
	 * @return value of bankcity
	 */
	public final java.lang.String getbankcity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.bankcity.toString());
	}

	/**
	 * Set value of bankcity
	 * @param bankcity
	 */
	public final void setbankcity(java.lang.String bankcity)
	{
		setbankcity(getContext(), bankcity);
	}

	/**
	 * Set value of bankcity
	 * @param context
	 * @param bankcity
	 */
	public final void setbankcity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bankcity)
	{
		getMendixObject().setValue(context, MemberNames.bankcity.toString(), bankcity);
	}

	/**
	 * @return value of step3completed
	 */
	public final java.lang.Boolean getstep3completed()
	{
		return getstep3completed(getContext());
	}

	/**
	 * @param context
	 * @return value of step3completed
	 */
	public final java.lang.Boolean getstep3completed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.step3completed.toString());
	}

	/**
	 * Set value of step3completed
	 * @param step3completed
	 */
	public final void setstep3completed(java.lang.Boolean step3completed)
	{
		setstep3completed(getContext(), step3completed);
	}

	/**
	 * Set value of step3completed
	 * @param context
	 * @param step3completed
	 */
	public final void setstep3completed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean step3completed)
	{
		getMendixObject().setValue(context, MemberNames.step3completed.toString(), step3completed);
	}

	/**
	 * @return value of dataid
	 */
	public final java.lang.Integer getdataid()
	{
		return getdataid(getContext());
	}

	/**
	 * @param context
	 * @return value of dataid
	 */
	public final java.lang.Integer getdataid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.dataid.toString());
	}

	/**
	 * Set value of dataid
	 * @param dataid
	 */
	public final void setdataid(java.lang.Integer dataid)
	{
		setdataid(getContext(), dataid);
	}

	/**
	 * Set value of dataid
	 * @param context
	 * @param dataid
	 */
	public final void setdataid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dataid)
	{
		getMendixObject().setValue(context, MemberNames.dataid.toString(), dataid);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bankdetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.bankdetails that = (myfirstmodule.proxies.bankdetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
