// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class basicdetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject basicdetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.basicdetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		membername("membername"),
		membercode("membercode"),
		taxstatus("taxstatus"),
		Dealername("Dealername"),
		step1completed("step1completed"),
		isactive("isactive"),
		Branchname("Branchname"),
		dataid("dataid");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public basicdetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected basicdetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject basicdetailsMendixObject)
	{
		if (basicdetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, basicdetailsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.basicdetailsMendixObject = basicdetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'basicdetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.basicdetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.basicdetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.basicdetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.basicdetails(context, mendixObject);
	}

	public static myfirstmodule.proxies.basicdetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.basicdetails.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.basicdetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.basicdetails.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of membername
	 */
	public final java.lang.String getmembername()
	{
		return getmembername(getContext());
	}

	/**
	 * @param context
	 * @return value of membername
	 */
	public final java.lang.String getmembername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.membername.toString());
	}

	/**
	 * Set value of membername
	 * @param membername
	 */
	public final void setmembername(java.lang.String membername)
	{
		setmembername(getContext(), membername);
	}

	/**
	 * Set value of membername
	 * @param context
	 * @param membername
	 */
	public final void setmembername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String membername)
	{
		getMendixObject().setValue(context, MemberNames.membername.toString(), membername);
	}

	/**
	 * @return value of membercode
	 */
	public final java.lang.String getmembercode()
	{
		return getmembercode(getContext());
	}

	/**
	 * @param context
	 * @return value of membercode
	 */
	public final java.lang.String getmembercode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.membercode.toString());
	}

	/**
	 * Set value of membercode
	 * @param membercode
	 */
	public final void setmembercode(java.lang.String membercode)
	{
		setmembercode(getContext(), membercode);
	}

	/**
	 * Set value of membercode
	 * @param context
	 * @param membercode
	 */
	public final void setmembercode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String membercode)
	{
		getMendixObject().setValue(context, MemberNames.membercode.toString(), membercode);
	}

	/**
	 * Set value of taxstatus
	 * @param taxstatus
	 */
	public final myfirstmodule.proxies.taxstatus gettaxstatus()
	{
		return gettaxstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of taxstatus
	 */
	public final myfirstmodule.proxies.taxstatus gettaxstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.taxstatus.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.taxstatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of taxstatus
	 * @param taxstatus
	 */
	public final void settaxstatus(myfirstmodule.proxies.taxstatus taxstatus)
	{
		settaxstatus(getContext(), taxstatus);
	}

	/**
	 * Set value of taxstatus
	 * @param context
	 * @param taxstatus
	 */
	public final void settaxstatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.taxstatus taxstatus)
	{
		if (taxstatus != null) {
			getMendixObject().setValue(context, MemberNames.taxstatus.toString(), taxstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.taxstatus.toString(), null);
		}
	}

	/**
	 * @return value of Dealername
	 */
	public final java.lang.String getDealername()
	{
		return getDealername(getContext());
	}

	/**
	 * @param context
	 * @return value of Dealername
	 */
	public final java.lang.String getDealername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Dealername.toString());
	}

	/**
	 * Set value of Dealername
	 * @param dealername
	 */
	public final void setDealername(java.lang.String dealername)
	{
		setDealername(getContext(), dealername);
	}

	/**
	 * Set value of Dealername
	 * @param context
	 * @param dealername
	 */
	public final void setDealername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dealername)
	{
		getMendixObject().setValue(context, MemberNames.Dealername.toString(), dealername);
	}

	/**
	 * @return value of step1completed
	 */
	public final java.lang.Boolean getstep1completed()
	{
		return getstep1completed(getContext());
	}

	/**
	 * @param context
	 * @return value of step1completed
	 */
	public final java.lang.Boolean getstep1completed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.step1completed.toString());
	}

	/**
	 * Set value of step1completed
	 * @param step1completed
	 */
	public final void setstep1completed(java.lang.Boolean step1completed)
	{
		setstep1completed(getContext(), step1completed);
	}

	/**
	 * Set value of step1completed
	 * @param context
	 * @param step1completed
	 */
	public final void setstep1completed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean step1completed)
	{
		getMendixObject().setValue(context, MemberNames.step1completed.toString(), step1completed);
	}

	/**
	 * @return value of isactive
	 */
	public final java.lang.Boolean getisactive()
	{
		return getisactive(getContext());
	}

	/**
	 * @param context
	 * @return value of isactive
	 */
	public final java.lang.Boolean getisactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isactive.toString());
	}

	/**
	 * Set value of isactive
	 * @param isactive
	 */
	public final void setisactive(java.lang.Boolean isactive)
	{
		setisactive(getContext(), isactive);
	}

	/**
	 * Set value of isactive
	 * @param context
	 * @param isactive
	 */
	public final void setisactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isactive)
	{
		getMendixObject().setValue(context, MemberNames.isactive.toString(), isactive);
	}

	/**
	 * @return value of Branchname
	 */
	public final java.lang.String getBranchname()
	{
		return getBranchname(getContext());
	}

	/**
	 * @param context
	 * @return value of Branchname
	 */
	public final java.lang.String getBranchname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Branchname.toString());
	}

	/**
	 * Set value of Branchname
	 * @param branchname
	 */
	public final void setBranchname(java.lang.String branchname)
	{
		setBranchname(getContext(), branchname);
	}

	/**
	 * Set value of Branchname
	 * @param context
	 * @param branchname
	 */
	public final void setBranchname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String branchname)
	{
		getMendixObject().setValue(context, MemberNames.Branchname.toString(), branchname);
	}

	/**
	 * @return value of dataid
	 */
	public final java.lang.Long getdataid()
	{
		return getdataid(getContext());
	}

	/**
	 * @param context
	 * @return value of dataid
	 */
	public final java.lang.Long getdataid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.dataid.toString());
	}

	/**
	 * Set value of dataid
	 * @param dataid
	 */
	public final void setdataid(java.lang.Long dataid)
	{
		setdataid(getContext(), dataid);
	}

	/**
	 * Set value of dataid
	 * @param context
	 * @param dataid
	 */
	public final void setdataid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long dataid)
	{
		getMendixObject().setValue(context, MemberNames.dataid.toString(), dataid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return basicdetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.basicdetails that = (myfirstmodule.proxies.basicdetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
