// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class clientdetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject clientdetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.clientdetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		clientcode("clientcode"),
		taxstatus("taxstatus"),
		pms("pms"),
		pmsentity("pmsentity"),
		holdingnature("holdingnature"),
		holdingtype("holdingtype"),
		redemptionpaymode("redemptionpaymode"),
		dataid("dataid");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public clientdetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected clientdetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject clientdetailsMendixObject)
	{
		if (clientdetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, clientdetailsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.clientdetailsMendixObject = clientdetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'clientdetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.clientdetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.clientdetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.clientdetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.clientdetails(context, mendixObject);
	}

	public static myfirstmodule.proxies.clientdetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.clientdetails.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.clientdetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.clientdetails.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of clientcode
	 */
	public final java.lang.String getclientcode()
	{
		return getclientcode(getContext());
	}

	/**
	 * @param context
	 * @return value of clientcode
	 */
	public final java.lang.String getclientcode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.clientcode.toString());
	}

	/**
	 * Set value of clientcode
	 * @param clientcode
	 */
	public final void setclientcode(java.lang.String clientcode)
	{
		setclientcode(getContext(), clientcode);
	}

	/**
	 * Set value of clientcode
	 * @param context
	 * @param clientcode
	 */
	public final void setclientcode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientcode)
	{
		getMendixObject().setValue(context, MemberNames.clientcode.toString(), clientcode);
	}

	/**
	 * Set value of taxstatus
	 * @param taxstatus
	 */
	public final myfirstmodule.proxies.taxstatus gettaxstatus()
	{
		return gettaxstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of taxstatus
	 */
	public final myfirstmodule.proxies.taxstatus gettaxstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.taxstatus.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.taxstatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of taxstatus
	 * @param taxstatus
	 */
	public final void settaxstatus(myfirstmodule.proxies.taxstatus taxstatus)
	{
		settaxstatus(getContext(), taxstatus);
	}

	/**
	 * Set value of taxstatus
	 * @param context
	 * @param taxstatus
	 */
	public final void settaxstatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.taxstatus taxstatus)
	{
		if (taxstatus != null) {
			getMendixObject().setValue(context, MemberNames.taxstatus.toString(), taxstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.taxstatus.toString(), null);
		}
	}

	/**
	 * Set value of pms
	 * @param pms
	 */
	public final myfirstmodule.proxies.pms getpms()
	{
		return getpms(getContext());
	}

	/**
	 * @param context
	 * @return value of pms
	 */
	public final myfirstmodule.proxies.pms getpms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.pms.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.pms.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of pms
	 * @param pms
	 */
	public final void setpms(myfirstmodule.proxies.pms pms)
	{
		setpms(getContext(), pms);
	}

	/**
	 * Set value of pms
	 * @param context
	 * @param pms
	 */
	public final void setpms(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.pms pms)
	{
		if (pms != null) {
			getMendixObject().setValue(context, MemberNames.pms.toString(), pms.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.pms.toString(), null);
		}
	}

	/**
	 * @return value of pmsentity
	 */
	public final java.lang.String getpmsentity()
	{
		return getpmsentity(getContext());
	}

	/**
	 * @param context
	 * @return value of pmsentity
	 */
	public final java.lang.String getpmsentity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.pmsentity.toString());
	}

	/**
	 * Set value of pmsentity
	 * @param pmsentity
	 */
	public final void setpmsentity(java.lang.String pmsentity)
	{
		setpmsentity(getContext(), pmsentity);
	}

	/**
	 * Set value of pmsentity
	 * @param context
	 * @param pmsentity
	 */
	public final void setpmsentity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pmsentity)
	{
		getMendixObject().setValue(context, MemberNames.pmsentity.toString(), pmsentity);
	}

	/**
	 * Set value of holdingnature
	 * @param holdingnature
	 */
	public final myfirstmodule.proxies.holdingnature getholdingnature()
	{
		return getholdingnature(getContext());
	}

	/**
	 * @param context
	 * @return value of holdingnature
	 */
	public final myfirstmodule.proxies.holdingnature getholdingnature(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.holdingnature.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.holdingnature.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of holdingnature
	 * @param holdingnature
	 */
	public final void setholdingnature(myfirstmodule.proxies.holdingnature holdingnature)
	{
		setholdingnature(getContext(), holdingnature);
	}

	/**
	 * Set value of holdingnature
	 * @param context
	 * @param holdingnature
	 */
	public final void setholdingnature(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.holdingnature holdingnature)
	{
		if (holdingnature != null) {
			getMendixObject().setValue(context, MemberNames.holdingnature.toString(), holdingnature.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.holdingnature.toString(), null);
		}
	}

	/**
	 * Set value of holdingtype
	 * @param holdingtype
	 */
	public final myfirstmodule.proxies.hodingtype getholdingtype()
	{
		return getholdingtype(getContext());
	}

	/**
	 * @param context
	 * @return value of holdingtype
	 */
	public final myfirstmodule.proxies.hodingtype getholdingtype(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.holdingtype.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.hodingtype.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of holdingtype
	 * @param holdingtype
	 */
	public final void setholdingtype(myfirstmodule.proxies.hodingtype holdingtype)
	{
		setholdingtype(getContext(), holdingtype);
	}

	/**
	 * Set value of holdingtype
	 * @param context
	 * @param holdingtype
	 */
	public final void setholdingtype(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.hodingtype holdingtype)
	{
		if (holdingtype != null) {
			getMendixObject().setValue(context, MemberNames.holdingtype.toString(), holdingtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.holdingtype.toString(), null);
		}
	}

	/**
	 * Set value of redemptionpaymode
	 * @param redemptionpaymode
	 */
	public final myfirstmodule.proxies.paymode getredemptionpaymode()
	{
		return getredemptionpaymode(getContext());
	}

	/**
	 * @param context
	 * @return value of redemptionpaymode
	 */
	public final myfirstmodule.proxies.paymode getredemptionpaymode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.redemptionpaymode.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.paymode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of redemptionpaymode
	 * @param redemptionpaymode
	 */
	public final void setredemptionpaymode(myfirstmodule.proxies.paymode redemptionpaymode)
	{
		setredemptionpaymode(getContext(), redemptionpaymode);
	}

	/**
	 * Set value of redemptionpaymode
	 * @param context
	 * @param redemptionpaymode
	 */
	public final void setredemptionpaymode(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.paymode redemptionpaymode)
	{
		if (redemptionpaymode != null) {
			getMendixObject().setValue(context, MemberNames.redemptionpaymode.toString(), redemptionpaymode.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.redemptionpaymode.toString(), null);
		}
	}

	/**
	 * @return value of dataid
	 */
	public final java.lang.Integer getdataid()
	{
		return getdataid(getContext());
	}

	/**
	 * @param context
	 * @return value of dataid
	 */
	public final java.lang.Integer getdataid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.dataid.toString());
	}

	/**
	 * Set value of dataid
	 * @param dataid
	 */
	public final void setdataid(java.lang.Integer dataid)
	{
		setdataid(getContext(), dataid);
	}

	/**
	 * Set value of dataid
	 * @param context
	 * @param dataid
	 */
	public final void setdataid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dataid)
	{
		getMendixObject().setValue(context, MemberNames.dataid.toString(), dataid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return clientdetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.clientdetails that = (myfirstmodule.proxies.clientdetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
