// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum countryresidence
{
	india(new java.lang.String[][] { new java.lang.String[] { "en_US", "India" }, new java.lang.String[] { "hi_IN", "भारत" } }),
	Japan(new java.lang.String[][] { new java.lang.String[] { "en_US", "Japan" } }),
	Bangladesh(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bangladesh" } }),
	australia(new java.lang.String[][] { new java.lang.String[] { "en_US", "australia" } }),
	Mynamar(new java.lang.String[][] { new java.lang.String[] { "en_US", "Mynamar" } }),
	Shrilanka(new java.lang.String[][] { new java.lang.String[] { "en_US", "Shrilanka" } }),
	Nepal(new java.lang.String[][] { new java.lang.String[] { "en_US", "Nepal" } }),
	China(new java.lang.String[][] { new java.lang.String[] { "en_US", "China" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private countryresidence(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
