// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class FACTA implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject fACTAMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.FACTA";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PAN("PAN"),
		clientname("clientname"),
		fathername("fathername"),
		spousename("spousename"),
		Adresstype("Adresstype"),
		placeofbirth("placeofbirth"),
		countryofbirth("countryofbirth"),
		wealthsource("wealthsource"),
		incomeslab("incomeslab"),
		cooperativeservicesector("cooperativeservicesector"),
		occupation("occupation"),
		occupationtypes("occupationtypes"),
		anyotherinformation("anyotherinformation"),
		networth("networth"),
		dateofnetworth("dateofnetworth"),
		npoform("npoform"),
		npodeclaration("npodeclaration"),
		nporegisterno("nporegisterno"),
		datasource("datasource"),
		logname("logname"),
		taxresident("taxresident"),
		countryresidence("countryresidence"),
		identifydoc("identifydoc"),
		taxpayerid("taxpayerid"),
		entityexemption("entityexemption"),
		ffi("ffi"),
		giin("giin"),
		nameofsponsor("nameofsponsor"),
		giinnotapplicable("giinnotapplicable"),
		nonfinancial("nonfinancial"),
		issin("issin"),
		nameoflistedcompany("nameoflistedcompany"),
		natureofrelation("natureofrelation"),
		exgangename("exgangename"),
		busineesname("busineesname"),
		subcategory("subcategory"),
		politicllyexposed("politicllyexposed"),
		step7completd("step7completd"),
		selfdeclaration("selfdeclaration"),
		dataid("dataid");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FACTA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FACTA(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fACTAMendixObject)
	{
		if (fACTAMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, fACTAMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.fACTAMendixObject = fACTAMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.FACTA initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.FACTA(context, mendixObject);
	}

	public static myfirstmodule.proxies.FACTA load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.FACTA.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.FACTA> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.FACTA.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of PAN
	 */
	public final java.lang.String getPAN()
	{
		return getPAN(getContext());
	}

	/**
	 * @param context
	 * @return value of PAN
	 */
	public final java.lang.String getPAN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PAN.toString());
	}

	/**
	 * Set value of PAN
	 * @param pan
	 */
	public final void setPAN(java.lang.String pan)
	{
		setPAN(getContext(), pan);
	}

	/**
	 * Set value of PAN
	 * @param context
	 * @param pan
	 */
	public final void setPAN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pan)
	{
		getMendixObject().setValue(context, MemberNames.PAN.toString(), pan);
	}

	/**
	 * @return value of clientname
	 */
	public final java.lang.String getclientname()
	{
		return getclientname(getContext());
	}

	/**
	 * @param context
	 * @return value of clientname
	 */
	public final java.lang.String getclientname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.clientname.toString());
	}

	/**
	 * Set value of clientname
	 * @param clientname
	 */
	public final void setclientname(java.lang.String clientname)
	{
		setclientname(getContext(), clientname);
	}

	/**
	 * Set value of clientname
	 * @param context
	 * @param clientname
	 */
	public final void setclientname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientname)
	{
		getMendixObject().setValue(context, MemberNames.clientname.toString(), clientname);
	}

	/**
	 * @return value of fathername
	 */
	public final java.lang.String getfathername()
	{
		return getfathername(getContext());
	}

	/**
	 * @param context
	 * @return value of fathername
	 */
	public final java.lang.String getfathername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.fathername.toString());
	}

	/**
	 * Set value of fathername
	 * @param fathername
	 */
	public final void setfathername(java.lang.String fathername)
	{
		setfathername(getContext(), fathername);
	}

	/**
	 * Set value of fathername
	 * @param context
	 * @param fathername
	 */
	public final void setfathername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fathername)
	{
		getMendixObject().setValue(context, MemberNames.fathername.toString(), fathername);
	}

	/**
	 * @return value of spousename
	 */
	public final java.lang.String getspousename()
	{
		return getspousename(getContext());
	}

	/**
	 * @param context
	 * @return value of spousename
	 */
	public final java.lang.String getspousename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.spousename.toString());
	}

	/**
	 * Set value of spousename
	 * @param spousename
	 */
	public final void setspousename(java.lang.String spousename)
	{
		setspousename(getContext(), spousename);
	}

	/**
	 * Set value of spousename
	 * @param context
	 * @param spousename
	 */
	public final void setspousename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String spousename)
	{
		getMendixObject().setValue(context, MemberNames.spousename.toString(), spousename);
	}

	/**
	 * Get value of Adresstype
	 * @param adresstype
	 */
	public final myfirstmodule.proxies.Adresstype2 getAdresstype()
	{
		return getAdresstype(getContext());
	}

	/**
	 * @param context
	 * @return value of Adresstype
	 */
	public final myfirstmodule.proxies.Adresstype2 getAdresstype(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Adresstype.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.Adresstype2.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Adresstype
	 * @param adresstype
	 */
	public final void setAdresstype(myfirstmodule.proxies.Adresstype2 adresstype)
	{
		setAdresstype(getContext(), adresstype);
	}

	/**
	 * Set value of Adresstype
	 * @param context
	 * @param adresstype
	 */
	public final void setAdresstype(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Adresstype2 adresstype)
	{
		if (adresstype != null) {
			getMendixObject().setValue(context, MemberNames.Adresstype.toString(), adresstype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Adresstype.toString(), null);
		}
	}

	/**
	 * @return value of placeofbirth
	 */
	public final java.lang.String getplaceofbirth()
	{
		return getplaceofbirth(getContext());
	}

	/**
	 * @param context
	 * @return value of placeofbirth
	 */
	public final java.lang.String getplaceofbirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.placeofbirth.toString());
	}

	/**
	 * Set value of placeofbirth
	 * @param placeofbirth
	 */
	public final void setplaceofbirth(java.lang.String placeofbirth)
	{
		setplaceofbirth(getContext(), placeofbirth);
	}

	/**
	 * Set value of placeofbirth
	 * @param context
	 * @param placeofbirth
	 */
	public final void setplaceofbirth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String placeofbirth)
	{
		getMendixObject().setValue(context, MemberNames.placeofbirth.toString(), placeofbirth);
	}

	/**
	 * @return value of countryofbirth
	 */
	public final java.lang.String getcountryofbirth()
	{
		return getcountryofbirth(getContext());
	}

	/**
	 * @param context
	 * @return value of countryofbirth
	 */
	public final java.lang.String getcountryofbirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.countryofbirth.toString());
	}

	/**
	 * Set value of countryofbirth
	 * @param countryofbirth
	 */
	public final void setcountryofbirth(java.lang.String countryofbirth)
	{
		setcountryofbirth(getContext(), countryofbirth);
	}

	/**
	 * Set value of countryofbirth
	 * @param context
	 * @param countryofbirth
	 */
	public final void setcountryofbirth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String countryofbirth)
	{
		getMendixObject().setValue(context, MemberNames.countryofbirth.toString(), countryofbirth);
	}

	/**
	 * Get value of wealthsource
	 * @param wealthsource
	 */
	public final myfirstmodule.proxies.wealthsource getwealthsource()
	{
		return getwealthsource(getContext());
	}

	/**
	 * @param context
	 * @return value of wealthsource
	 */
	public final myfirstmodule.proxies.wealthsource getwealthsource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.wealthsource.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.wealthsource.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of wealthsource
	 * @param wealthsource
	 */
	public final void setwealthsource(myfirstmodule.proxies.wealthsource wealthsource)
	{
		setwealthsource(getContext(), wealthsource);
	}

	/**
	 * Set value of wealthsource
	 * @param context
	 * @param wealthsource
	 */
	public final void setwealthsource(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.wealthsource wealthsource)
	{
		if (wealthsource != null) {
			getMendixObject().setValue(context, MemberNames.wealthsource.toString(), wealthsource.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.wealthsource.toString(), null);
		}
	}

	/**
	 * Get value of incomeslab
	 * @param incomeslab
	 */
	public final myfirstmodule.proxies.incomeslab getincomeslab()
	{
		return getincomeslab(getContext());
	}

	/**
	 * @param context
	 * @return value of incomeslab
	 */
	public final myfirstmodule.proxies.incomeslab getincomeslab(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.incomeslab.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.incomeslab.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of incomeslab
	 * @param incomeslab
	 */
	public final void setincomeslab(myfirstmodule.proxies.incomeslab incomeslab)
	{
		setincomeslab(getContext(), incomeslab);
	}

	/**
	 * Set value of incomeslab
	 * @param context
	 * @param incomeslab
	 */
	public final void setincomeslab(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.incomeslab incomeslab)
	{
		if (incomeslab != null) {
			getMendixObject().setValue(context, MemberNames.incomeslab.toString(), incomeslab.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.incomeslab.toString(), null);
		}
	}

	/**
	 * Get value of cooperativeservicesector
	 * @param cooperativeservicesector
	 */
	public final myfirstmodule.proxies.servicesector getcooperativeservicesector()
	{
		return getcooperativeservicesector(getContext());
	}

	/**
	 * @param context
	 * @return value of cooperativeservicesector
	 */
	public final myfirstmodule.proxies.servicesector getcooperativeservicesector(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.cooperativeservicesector.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.servicesector.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of cooperativeservicesector
	 * @param cooperativeservicesector
	 */
	public final void setcooperativeservicesector(myfirstmodule.proxies.servicesector cooperativeservicesector)
	{
		setcooperativeservicesector(getContext(), cooperativeservicesector);
	}

	/**
	 * Set value of cooperativeservicesector
	 * @param context
	 * @param cooperativeservicesector
	 */
	public final void setcooperativeservicesector(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.servicesector cooperativeservicesector)
	{
		if (cooperativeservicesector != null) {
			getMendixObject().setValue(context, MemberNames.cooperativeservicesector.toString(), cooperativeservicesector.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.cooperativeservicesector.toString(), null);
		}
	}

	/**
	 * Get value of occupation
	 * @param occupation
	 */
	public final myfirstmodule.proxies.occupation getoccupation()
	{
		return getoccupation(getContext());
	}

	/**
	 * @param context
	 * @return value of occupation
	 */
	public final myfirstmodule.proxies.occupation getoccupation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.occupation.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.occupation.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of occupation
	 * @param occupation
	 */
	public final void setoccupation(myfirstmodule.proxies.occupation occupation)
	{
		setoccupation(getContext(), occupation);
	}

	/**
	 * Set value of occupation
	 * @param context
	 * @param occupation
	 */
	public final void setoccupation(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.occupation occupation)
	{
		if (occupation != null) {
			getMendixObject().setValue(context, MemberNames.occupation.toString(), occupation.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.occupation.toString(), null);
		}
	}

	/**
	 * Get value of occupationtypes
	 * @param occupationtypes
	 */
	public final myfirstmodule.proxies.occupatuiontype getoccupationtypes()
	{
		return getoccupationtypes(getContext());
	}

	/**
	 * @param context
	 * @return value of occupationtypes
	 */
	public final myfirstmodule.proxies.occupatuiontype getoccupationtypes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.occupationtypes.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.occupatuiontype.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of occupationtypes
	 * @param occupationtypes
	 */
	public final void setoccupationtypes(myfirstmodule.proxies.occupatuiontype occupationtypes)
	{
		setoccupationtypes(getContext(), occupationtypes);
	}

	/**
	 * Set value of occupationtypes
	 * @param context
	 * @param occupationtypes
	 */
	public final void setoccupationtypes(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.occupatuiontype occupationtypes)
	{
		if (occupationtypes != null) {
			getMendixObject().setValue(context, MemberNames.occupationtypes.toString(), occupationtypes.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.occupationtypes.toString(), null);
		}
	}

	/**
	 * @return value of anyotherinformation
	 */
	public final java.lang.String getanyotherinformation()
	{
		return getanyotherinformation(getContext());
	}

	/**
	 * @param context
	 * @return value of anyotherinformation
	 */
	public final java.lang.String getanyotherinformation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.anyotherinformation.toString());
	}

	/**
	 * Set value of anyotherinformation
	 * @param anyotherinformation
	 */
	public final void setanyotherinformation(java.lang.String anyotherinformation)
	{
		setanyotherinformation(getContext(), anyotherinformation);
	}

	/**
	 * Set value of anyotherinformation
	 * @param context
	 * @param anyotherinformation
	 */
	public final void setanyotherinformation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String anyotherinformation)
	{
		getMendixObject().setValue(context, MemberNames.anyotherinformation.toString(), anyotherinformation);
	}

	/**
	 * @return value of networth
	 */
	public final java.lang.String getnetworth()
	{
		return getnetworth(getContext());
	}

	/**
	 * @param context
	 * @return value of networth
	 */
	public final java.lang.String getnetworth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.networth.toString());
	}

	/**
	 * Set value of networth
	 * @param networth
	 */
	public final void setnetworth(java.lang.String networth)
	{
		setnetworth(getContext(), networth);
	}

	/**
	 * Set value of networth
	 * @param context
	 * @param networth
	 */
	public final void setnetworth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String networth)
	{
		getMendixObject().setValue(context, MemberNames.networth.toString(), networth);
	}

	/**
	 * @return value of dateofnetworth
	 */
	public final java.util.Date getdateofnetworth()
	{
		return getdateofnetworth(getContext());
	}

	/**
	 * @param context
	 * @return value of dateofnetworth
	 */
	public final java.util.Date getdateofnetworth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.dateofnetworth.toString());
	}

	/**
	 * Set value of dateofnetworth
	 * @param dateofnetworth
	 */
	public final void setdateofnetworth(java.util.Date dateofnetworth)
	{
		setdateofnetworth(getContext(), dateofnetworth);
	}

	/**
	 * Set value of dateofnetworth
	 * @param context
	 * @param dateofnetworth
	 */
	public final void setdateofnetworth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofnetworth)
	{
		getMendixObject().setValue(context, MemberNames.dateofnetworth.toString(), dateofnetworth);
	}

	/**
	 * Get value of npoform
	 * @param npoform
	 */
	public final myfirstmodule.proxies.npoform getnpoform()
	{
		return getnpoform(getContext());
	}

	/**
	 * @param context
	 * @return value of npoform
	 */
	public final myfirstmodule.proxies.npoform getnpoform(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.npoform.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.npoform.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of npoform
	 * @param npoform
	 */
	public final void setnpoform(myfirstmodule.proxies.npoform npoform)
	{
		setnpoform(getContext(), npoform);
	}

	/**
	 * Set value of npoform
	 * @param context
	 * @param npoform
	 */
	public final void setnpoform(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.npoform npoform)
	{
		if (npoform != null) {
			getMendixObject().setValue(context, MemberNames.npoform.toString(), npoform.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.npoform.toString(), null);
		}
	}

	/**
	 * Get value of npodeclaration
	 * @param npodeclaration
	 */
	public final myfirstmodule.proxies.npodeclaration getnpodeclaration()
	{
		return getnpodeclaration(getContext());
	}

	/**
	 * @param context
	 * @return value of npodeclaration
	 */
	public final myfirstmodule.proxies.npodeclaration getnpodeclaration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.npodeclaration.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.npodeclaration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of npodeclaration
	 * @param npodeclaration
	 */
	public final void setnpodeclaration(myfirstmodule.proxies.npodeclaration npodeclaration)
	{
		setnpodeclaration(getContext(), npodeclaration);
	}

	/**
	 * Set value of npodeclaration
	 * @param context
	 * @param npodeclaration
	 */
	public final void setnpodeclaration(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.npodeclaration npodeclaration)
	{
		if (npodeclaration != null) {
			getMendixObject().setValue(context, MemberNames.npodeclaration.toString(), npodeclaration.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.npodeclaration.toString(), null);
		}
	}

	/**
	 * @return value of nporegisterno
	 */
	public final java.lang.String getnporegisterno()
	{
		return getnporegisterno(getContext());
	}

	/**
	 * @param context
	 * @return value of nporegisterno
	 */
	public final java.lang.String getnporegisterno(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nporegisterno.toString());
	}

	/**
	 * Set value of nporegisterno
	 * @param nporegisterno
	 */
	public final void setnporegisterno(java.lang.String nporegisterno)
	{
		setnporegisterno(getContext(), nporegisterno);
	}

	/**
	 * Set value of nporegisterno
	 * @param context
	 * @param nporegisterno
	 */
	public final void setnporegisterno(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nporegisterno)
	{
		getMendixObject().setValue(context, MemberNames.nporegisterno.toString(), nporegisterno);
	}

	/**
	 * Get value of datasource
	 * @param datasource
	 */
	public final myfirstmodule.proxies.datsource getdatasource()
	{
		return getdatasource(getContext());
	}

	/**
	 * @param context
	 * @return value of datasource
	 */
	public final myfirstmodule.proxies.datsource getdatasource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.datasource.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.datsource.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of datasource
	 * @param datasource
	 */
	public final void setdatasource(myfirstmodule.proxies.datsource datasource)
	{
		setdatasource(getContext(), datasource);
	}

	/**
	 * Set value of datasource
	 * @param context
	 * @param datasource
	 */
	public final void setdatasource(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.datsource datasource)
	{
		if (datasource != null) {
			getMendixObject().setValue(context, MemberNames.datasource.toString(), datasource.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.datasource.toString(), null);
		}
	}

	/**
	 * @return value of logname
	 */
	public final java.lang.String getlogname()
	{
		return getlogname(getContext());
	}

	/**
	 * @param context
	 * @return value of logname
	 */
	public final java.lang.String getlogname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.logname.toString());
	}

	/**
	 * Set value of logname
	 * @param logname
	 */
	public final void setlogname(java.lang.String logname)
	{
		setlogname(getContext(), logname);
	}

	/**
	 * Set value of logname
	 * @param context
	 * @param logname
	 */
	public final void setlogname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String logname)
	{
		getMendixObject().setValue(context, MemberNames.logname.toString(), logname);
	}

	/**
	 * Get value of taxresident
	 * @param taxresident
	 */
	public final myfirstmodule.proxies.taxresident gettaxresident()
	{
		return gettaxresident(getContext());
	}

	/**
	 * @param context
	 * @return value of taxresident
	 */
	public final myfirstmodule.proxies.taxresident gettaxresident(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.taxresident.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.taxresident.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of taxresident
	 * @param taxresident
	 */
	public final void settaxresident(myfirstmodule.proxies.taxresident taxresident)
	{
		settaxresident(getContext(), taxresident);
	}

	/**
	 * Set value of taxresident
	 * @param context
	 * @param taxresident
	 */
	public final void settaxresident(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.taxresident taxresident)
	{
		if (taxresident != null) {
			getMendixObject().setValue(context, MemberNames.taxresident.toString(), taxresident.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.taxresident.toString(), null);
		}
	}

	/**
	 * Get value of countryresidence
	 * @param countryresidence
	 */
	public final myfirstmodule.proxies.countryresidence getcountryresidence()
	{
		return getcountryresidence(getContext());
	}

	/**
	 * @param context
	 * @return value of countryresidence
	 */
	public final myfirstmodule.proxies.countryresidence getcountryresidence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.countryresidence.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.countryresidence.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of countryresidence
	 * @param countryresidence
	 */
	public final void setcountryresidence(myfirstmodule.proxies.countryresidence countryresidence)
	{
		setcountryresidence(getContext(), countryresidence);
	}

	/**
	 * Set value of countryresidence
	 * @param context
	 * @param countryresidence
	 */
	public final void setcountryresidence(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.countryresidence countryresidence)
	{
		if (countryresidence != null) {
			getMendixObject().setValue(context, MemberNames.countryresidence.toString(), countryresidence.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.countryresidence.toString(), null);
		}
	}

	/**
	 * Get value of identifydoc
	 * @param identifydoc
	 */
	public final myfirstmodule.proxies.iddoc getidentifydoc()
	{
		return getidentifydoc(getContext());
	}

	/**
	 * @param context
	 * @return value of identifydoc
	 */
	public final myfirstmodule.proxies.iddoc getidentifydoc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.identifydoc.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.iddoc.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of identifydoc
	 * @param identifydoc
	 */
	public final void setidentifydoc(myfirstmodule.proxies.iddoc identifydoc)
	{
		setidentifydoc(getContext(), identifydoc);
	}

	/**
	 * Set value of identifydoc
	 * @param context
	 * @param identifydoc
	 */
	public final void setidentifydoc(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.iddoc identifydoc)
	{
		if (identifydoc != null) {
			getMendixObject().setValue(context, MemberNames.identifydoc.toString(), identifydoc.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.identifydoc.toString(), null);
		}
	}

	/**
	 * @return value of taxpayerid
	 */
	public final java.lang.String gettaxpayerid()
	{
		return gettaxpayerid(getContext());
	}

	/**
	 * @param context
	 * @return value of taxpayerid
	 */
	public final java.lang.String gettaxpayerid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.taxpayerid.toString());
	}

	/**
	 * Set value of taxpayerid
	 * @param taxpayerid
	 */
	public final void settaxpayerid(java.lang.String taxpayerid)
	{
		settaxpayerid(getContext(), taxpayerid);
	}

	/**
	 * Set value of taxpayerid
	 * @param context
	 * @param taxpayerid
	 */
	public final void settaxpayerid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taxpayerid)
	{
		getMendixObject().setValue(context, MemberNames.taxpayerid.toString(), taxpayerid);
	}

	/**
	 * Get value of entityexemption
	 * @param entityexemption
	 */
	public final myfirstmodule.proxies.entityexemptioncode getentityexemption()
	{
		return getentityexemption(getContext());
	}

	/**
	 * @param context
	 * @return value of entityexemption
	 */
	public final myfirstmodule.proxies.entityexemptioncode getentityexemption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.entityexemption.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.entityexemptioncode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of entityexemption
	 * @param entityexemption
	 */
	public final void setentityexemption(myfirstmodule.proxies.entityexemptioncode entityexemption)
	{
		setentityexemption(getContext(), entityexemption);
	}

	/**
	 * Set value of entityexemption
	 * @param context
	 * @param entityexemption
	 */
	public final void setentityexemption(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.entityexemptioncode entityexemption)
	{
		if (entityexemption != null) {
			getMendixObject().setValue(context, MemberNames.entityexemption.toString(), entityexemption.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.entityexemption.toString(), null);
		}
	}

	/**
	 * Get value of ffi
	 * @param ffi
	 */
	public final myfirstmodule.proxies.ffi getffi()
	{
		return getffi(getContext());
	}

	/**
	 * @param context
	 * @return value of ffi
	 */
	public final myfirstmodule.proxies.ffi getffi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ffi.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.ffi.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ffi
	 * @param ffi
	 */
	public final void setffi(myfirstmodule.proxies.ffi ffi)
	{
		setffi(getContext(), ffi);
	}

	/**
	 * Set value of ffi
	 * @param context
	 * @param ffi
	 */
	public final void setffi(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ffi ffi)
	{
		if (ffi != null) {
			getMendixObject().setValue(context, MemberNames.ffi.toString(), ffi.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ffi.toString(), null);
		}
	}

	/**
	 * @return value of giin
	 */
	public final java.lang.String getgiin()
	{
		return getgiin(getContext());
	}

	/**
	 * @param context
	 * @return value of giin
	 */
	public final java.lang.String getgiin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.giin.toString());
	}

	/**
	 * Set value of giin
	 * @param giin
	 */
	public final void setgiin(java.lang.String giin)
	{
		setgiin(getContext(), giin);
	}

	/**
	 * Set value of giin
	 * @param context
	 * @param giin
	 */
	public final void setgiin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String giin)
	{
		getMendixObject().setValue(context, MemberNames.giin.toString(), giin);
	}

	/**
	 * @return value of nameofsponsor
	 */
	public final java.lang.String getnameofsponsor()
	{
		return getnameofsponsor(getContext());
	}

	/**
	 * @param context
	 * @return value of nameofsponsor
	 */
	public final java.lang.String getnameofsponsor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nameofsponsor.toString());
	}

	/**
	 * Set value of nameofsponsor
	 * @param nameofsponsor
	 */
	public final void setnameofsponsor(java.lang.String nameofsponsor)
	{
		setnameofsponsor(getContext(), nameofsponsor);
	}

	/**
	 * Set value of nameofsponsor
	 * @param context
	 * @param nameofsponsor
	 */
	public final void setnameofsponsor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nameofsponsor)
	{
		getMendixObject().setValue(context, MemberNames.nameofsponsor.toString(), nameofsponsor);
	}

	/**
	 * Get value of giinnotapplicable
	 * @param giinnotapplicable
	 */
	public final myfirstmodule.proxies.giinapllicable getgiinnotapplicable()
	{
		return getgiinnotapplicable(getContext());
	}

	/**
	 * @param context
	 * @return value of giinnotapplicable
	 */
	public final myfirstmodule.proxies.giinapllicable getgiinnotapplicable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.giinnotapplicable.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.giinapllicable.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of giinnotapplicable
	 * @param giinnotapplicable
	 */
	public final void setgiinnotapplicable(myfirstmodule.proxies.giinapllicable giinnotapplicable)
	{
		setgiinnotapplicable(getContext(), giinnotapplicable);
	}

	/**
	 * Set value of giinnotapplicable
	 * @param context
	 * @param giinnotapplicable
	 */
	public final void setgiinnotapplicable(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.giinapllicable giinnotapplicable)
	{
		if (giinnotapplicable != null) {
			getMendixObject().setValue(context, MemberNames.giinnotapplicable.toString(), giinnotapplicable.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.giinnotapplicable.toString(), null);
		}
	}

	/**
	 * Get value of nonfinancial
	 * @param nonfinancial
	 */
	public final myfirstmodule.proxies.nonfinancial getnonfinancial()
	{
		return getnonfinancial(getContext());
	}

	/**
	 * @param context
	 * @return value of nonfinancial
	 */
	public final myfirstmodule.proxies.nonfinancial getnonfinancial(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.nonfinancial.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.nonfinancial.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of nonfinancial
	 * @param nonfinancial
	 */
	public final void setnonfinancial(myfirstmodule.proxies.nonfinancial nonfinancial)
	{
		setnonfinancial(getContext(), nonfinancial);
	}

	/**
	 * Set value of nonfinancial
	 * @param context
	 * @param nonfinancial
	 */
	public final void setnonfinancial(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.nonfinancial nonfinancial)
	{
		if (nonfinancial != null) {
			getMendixObject().setValue(context, MemberNames.nonfinancial.toString(), nonfinancial.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.nonfinancial.toString(), null);
		}
	}

	/**
	 * @return value of issin
	 */
	public final java.lang.String getissin()
	{
		return getissin(getContext());
	}

	/**
	 * @param context
	 * @return value of issin
	 */
	public final java.lang.String getissin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.issin.toString());
	}

	/**
	 * Set value of issin
	 * @param issin
	 */
	public final void setissin(java.lang.String issin)
	{
		setissin(getContext(), issin);
	}

	/**
	 * Set value of issin
	 * @param context
	 * @param issin
	 */
	public final void setissin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String issin)
	{
		getMendixObject().setValue(context, MemberNames.issin.toString(), issin);
	}

	/**
	 * @return value of nameoflistedcompany
	 */
	public final java.lang.String getnameoflistedcompany()
	{
		return getnameoflistedcompany(getContext());
	}

	/**
	 * @param context
	 * @return value of nameoflistedcompany
	 */
	public final java.lang.String getnameoflistedcompany(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.nameoflistedcompany.toString());
	}

	/**
	 * Set value of nameoflistedcompany
	 * @param nameoflistedcompany
	 */
	public final void setnameoflistedcompany(java.lang.String nameoflistedcompany)
	{
		setnameoflistedcompany(getContext(), nameoflistedcompany);
	}

	/**
	 * Set value of nameoflistedcompany
	 * @param context
	 * @param nameoflistedcompany
	 */
	public final void setnameoflistedcompany(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nameoflistedcompany)
	{
		getMendixObject().setValue(context, MemberNames.nameoflistedcompany.toString(), nameoflistedcompany);
	}

	/**
	 * Get value of natureofrelation
	 * @param natureofrelation
	 */
	public final myfirstmodule.proxies.natureofrelation getnatureofrelation()
	{
		return getnatureofrelation(getContext());
	}

	/**
	 * @param context
	 * @return value of natureofrelation
	 */
	public final myfirstmodule.proxies.natureofrelation getnatureofrelation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.natureofrelation.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.natureofrelation.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of natureofrelation
	 * @param natureofrelation
	 */
	public final void setnatureofrelation(myfirstmodule.proxies.natureofrelation natureofrelation)
	{
		setnatureofrelation(getContext(), natureofrelation);
	}

	/**
	 * Set value of natureofrelation
	 * @param context
	 * @param natureofrelation
	 */
	public final void setnatureofrelation(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.natureofrelation natureofrelation)
	{
		if (natureofrelation != null) {
			getMendixObject().setValue(context, MemberNames.natureofrelation.toString(), natureofrelation.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.natureofrelation.toString(), null);
		}
	}

	/**
	 * @return value of exgangename
	 */
	public final java.lang.String getexgangename()
	{
		return getexgangename(getContext());
	}

	/**
	 * @param context
	 * @return value of exgangename
	 */
	public final java.lang.String getexgangename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.exgangename.toString());
	}

	/**
	 * Set value of exgangename
	 * @param exgangename
	 */
	public final void setexgangename(java.lang.String exgangename)
	{
		setexgangename(getContext(), exgangename);
	}

	/**
	 * Set value of exgangename
	 * @param context
	 * @param exgangename
	 */
	public final void setexgangename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String exgangename)
	{
		getMendixObject().setValue(context, MemberNames.exgangename.toString(), exgangename);
	}

	/**
	 * @return value of busineesname
	 */
	public final java.lang.String getbusineesname()
	{
		return getbusineesname(getContext());
	}

	/**
	 * @param context
	 * @return value of busineesname
	 */
	public final java.lang.String getbusineesname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.busineesname.toString());
	}

	/**
	 * Set value of busineesname
	 * @param busineesname
	 */
	public final void setbusineesname(java.lang.String busineesname)
	{
		setbusineesname(getContext(), busineesname);
	}

	/**
	 * Set value of busineesname
	 * @param context
	 * @param busineesname
	 */
	public final void setbusineesname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String busineesname)
	{
		getMendixObject().setValue(context, MemberNames.busineesname.toString(), busineesname);
	}

	/**
	 * Get value of subcategory
	 * @param subcategory
	 */
	public final myfirstmodule.proxies.subcategory getsubcategory()
	{
		return getsubcategory(getContext());
	}

	/**
	 * @param context
	 * @return value of subcategory
	 */
	public final myfirstmodule.proxies.subcategory getsubcategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.subcategory.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.subcategory.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of subcategory
	 * @param subcategory
	 */
	public final void setsubcategory(myfirstmodule.proxies.subcategory subcategory)
	{
		setsubcategory(getContext(), subcategory);
	}

	/**
	 * Set value of subcategory
	 * @param context
	 * @param subcategory
	 */
	public final void setsubcategory(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.subcategory subcategory)
	{
		if (subcategory != null) {
			getMendixObject().setValue(context, MemberNames.subcategory.toString(), subcategory.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.subcategory.toString(), null);
		}
	}

	/**
	 * Get value of politicllyexposed
	 * @param politicllyexposed
	 */
	public final myfirstmodule.proxies.politicallyexposed getpoliticllyexposed()
	{
		return getpoliticllyexposed(getContext());
	}

	/**
	 * @param context
	 * @return value of politicllyexposed
	 */
	public final myfirstmodule.proxies.politicallyexposed getpoliticllyexposed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.politicllyexposed.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.politicallyexposed.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of politicllyexposed
	 * @param politicllyexposed
	 */
	public final void setpoliticllyexposed(myfirstmodule.proxies.politicallyexposed politicllyexposed)
	{
		setpoliticllyexposed(getContext(), politicllyexposed);
	}

	/**
	 * Set value of politicllyexposed
	 * @param context
	 * @param politicllyexposed
	 */
	public final void setpoliticllyexposed(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.politicallyexposed politicllyexposed)
	{
		if (politicllyexposed != null) {
			getMendixObject().setValue(context, MemberNames.politicllyexposed.toString(), politicllyexposed.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.politicllyexposed.toString(), null);
		}
	}

	/**
	 * @return value of step7completd
	 */
	public final java.lang.Boolean getstep7completd()
	{
		return getstep7completd(getContext());
	}

	/**
	 * @param context
	 * @return value of step7completd
	 */
	public final java.lang.Boolean getstep7completd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.step7completd.toString());
	}

	/**
	 * Set value of step7completd
	 * @param step7completd
	 */
	public final void setstep7completd(java.lang.Boolean step7completd)
	{
		setstep7completd(getContext(), step7completd);
	}

	/**
	 * Set value of step7completd
	 * @param context
	 * @param step7completd
	 */
	public final void setstep7completd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean step7completd)
	{
		getMendixObject().setValue(context, MemberNames.step7completd.toString(), step7completd);
	}

	/**
	 * @return value of selfdeclaration
	 */
	public final java.lang.Boolean getselfdeclaration()
	{
		return getselfdeclaration(getContext());
	}

	/**
	 * @param context
	 * @return value of selfdeclaration
	 */
	public final java.lang.Boolean getselfdeclaration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.selfdeclaration.toString());
	}

	/**
	 * Set value of selfdeclaration
	 * @param selfdeclaration
	 */
	public final void setselfdeclaration(java.lang.Boolean selfdeclaration)
	{
		setselfdeclaration(getContext(), selfdeclaration);
	}

	/**
	 * Set value of selfdeclaration
	 * @param context
	 * @param selfdeclaration
	 */
	public final void setselfdeclaration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selfdeclaration)
	{
		getMendixObject().setValue(context, MemberNames.selfdeclaration.toString(), selfdeclaration);
	}

	/**
	 * @return value of dataid
	 */
	public final java.lang.Integer getdataid()
	{
		return getdataid(getContext());
	}

	/**
	 * @param context
	 * @return value of dataid
	 */
	public final java.lang.Integer getdataid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.dataid.toString());
	}

	/**
	 * Set value of dataid
	 * @param dataid
	 */
	public final void setdataid(java.lang.Integer dataid)
	{
		setdataid(getContext(), dataid);
	}

	/**
	 * Set value of dataid
	 * @param context
	 * @param dataid
	 */
	public final void setdataid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dataid)
	{
		getMendixObject().setValue(context, MemberNames.dataid.toString(), dataid);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return fACTAMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.FACTA that = (myfirstmodule.proxies.FACTA) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
