// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum ffi
{
	ffi(new java.lang.String[][] { new java.lang.String[] { "en_US", "ffi" }, new java.lang.String[] { "hi_IN", "FFI" } }),
	drnfe(new java.lang.String[][] { new java.lang.String[] { "en_US", "drnfe" }, new java.lang.String[] { "hi_IN", "डीआरएनएफई" } }),
	na(new java.lang.String[][] { new java.lang.String[] { "en_US", "na" }, new java.lang.String[] { "hi_IN", "NA" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ffi(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
