// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum holdingnature
{
	single_holding(new java.lang.String[][] { new java.lang.String[] { "en_US", "Single Holding" }, new java.lang.String[] { "hi_IN", "एकल होल्डिंग" } }),
	joint_holding(new java.lang.String[][] { new java.lang.String[] { "en_US", "Joint Holding" }, new java.lang.String[] { "hi_IN", "संयुक्त होल्डिंग" } }),
	anyone_or_survivorholding(new java.lang.String[][] { new java.lang.String[] { "en_US", "Anyone or SurvivorHolding" }, new java.lang.String[] { "hi_IN", "कोई भी या उत्तराधिकारी जो होल्डिंग कर रहा है" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private holdingnature(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
