// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class holderdetails implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject holderdetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.holderdetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		pan("pan"),
		firstname("firstname"),
		lastname("lastname"),
		dateofregister("dateofregister"),
		gender("gender"),
		taxstatus("taxstatus"),
		kyctype("kyctype"),
		mobilenumber("mobilenumber"),
		mobiledeclaration("mobiledeclaration"),
		emailid("emailid"),
		emaildeclaration("emaildeclaration"),
		pancategory("pancategory"),
		middlename("middlename"),
		step2completed("step2completed"),
		occuptation("occuptation"),
		panexempt("panexempt"),
		pkern("pkern"),
		dataid("dataid");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public holderdetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected holderdetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject holderdetailsMendixObject)
	{
		if (holderdetailsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, holderdetailsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.holderdetailsMendixObject = holderdetailsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.holderdetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.holderdetails(context, mendixObject);
	}

	public static myfirstmodule.proxies.holderdetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.holderdetails.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.holderdetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.holderdetails.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of pan
	 */
	public final java.lang.String getpan()
	{
		return getpan(getContext());
	}

	/**
	 * @param context
	 * @return value of pan
	 */
	public final java.lang.String getpan(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.pan.toString());
	}

	/**
	 * Set value of pan
	 * @param pan
	 */
	public final void setpan(java.lang.String pan)
	{
		setpan(getContext(), pan);
	}

	/**
	 * Set value of pan
	 * @param context
	 * @param pan
	 */
	public final void setpan(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pan)
	{
		getMendixObject().setValue(context, MemberNames.pan.toString(), pan);
	}

	/**
	 * @return value of firstname
	 */
	public final java.lang.String getfirstname()
	{
		return getfirstname(getContext());
	}

	/**
	 * @param context
	 * @return value of firstname
	 */
	public final java.lang.String getfirstname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.firstname.toString());
	}

	/**
	 * Set value of firstname
	 * @param firstname
	 */
	public final void setfirstname(java.lang.String firstname)
	{
		setfirstname(getContext(), firstname);
	}

	/**
	 * Set value of firstname
	 * @param context
	 * @param firstname
	 */
	public final void setfirstname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.firstname.toString(), firstname);
	}

	/**
	 * @return value of lastname
	 */
	public final java.lang.String getlastname()
	{
		return getlastname(getContext());
	}

	/**
	 * @param context
	 * @return value of lastname
	 */
	public final java.lang.String getlastname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.lastname.toString());
	}

	/**
	 * Set value of lastname
	 * @param lastname
	 */
	public final void setlastname(java.lang.String lastname)
	{
		setlastname(getContext(), lastname);
	}

	/**
	 * Set value of lastname
	 * @param context
	 * @param lastname
	 */
	public final void setlastname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.lastname.toString(), lastname);
	}

	/**
	 * @return value of dateofregister
	 */
	public final java.util.Date getdateofregister()
	{
		return getdateofregister(getContext());
	}

	/**
	 * @param context
	 * @return value of dateofregister
	 */
	public final java.util.Date getdateofregister(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.dateofregister.toString());
	}

	/**
	 * Set value of dateofregister
	 * @param dateofregister
	 */
	public final void setdateofregister(java.util.Date dateofregister)
	{
		setdateofregister(getContext(), dateofregister);
	}

	/**
	 * Set value of dateofregister
	 * @param context
	 * @param dateofregister
	 */
	public final void setdateofregister(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofregister)
	{
		getMendixObject().setValue(context, MemberNames.dateofregister.toString(), dateofregister);
	}

	/**
	 * Get value of gender
	 * @param gender
	 */
	public final myfirstmodule.proxies.gender getgender()
	{
		return getgender(getContext());
	}

	/**
	 * @param context
	 * @return value of gender
	 */
	public final myfirstmodule.proxies.gender getgender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.gender.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.gender.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of gender
	 * @param gender
	 */
	public final void setgender(myfirstmodule.proxies.gender gender)
	{
		setgender(getContext(), gender);
	}

	/**
	 * Set value of gender
	 * @param context
	 * @param gender
	 */
	public final void setgender(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.gender gender)
	{
		if (gender != null) {
			getMendixObject().setValue(context, MemberNames.gender.toString(), gender.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.gender.toString(), null);
		}
	}

	/**
	 * Get value of taxstatus
	 * @param taxstatus
	 */
	public final myfirstmodule.proxies.taxstatus gettaxstatus()
	{
		return gettaxstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of taxstatus
	 */
	public final myfirstmodule.proxies.taxstatus gettaxstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.taxstatus.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.taxstatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of taxstatus
	 * @param taxstatus
	 */
	public final void settaxstatus(myfirstmodule.proxies.taxstatus taxstatus)
	{
		settaxstatus(getContext(), taxstatus);
	}

	/**
	 * Set value of taxstatus
	 * @param context
	 * @param taxstatus
	 */
	public final void settaxstatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.taxstatus taxstatus)
	{
		if (taxstatus != null) {
			getMendixObject().setValue(context, MemberNames.taxstatus.toString(), taxstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.taxstatus.toString(), null);
		}
	}

	/**
	 * Get value of kyctype
	 * @param kyctype
	 */
	public final myfirstmodule.proxies.kyctype getkyctype()
	{
		return getkyctype(getContext());
	}

	/**
	 * @param context
	 * @return value of kyctype
	 */
	public final myfirstmodule.proxies.kyctype getkyctype(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.kyctype.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.kyctype.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of kyctype
	 * @param kyctype
	 */
	public final void setkyctype(myfirstmodule.proxies.kyctype kyctype)
	{
		setkyctype(getContext(), kyctype);
	}

	/**
	 * Set value of kyctype
	 * @param context
	 * @param kyctype
	 */
	public final void setkyctype(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.kyctype kyctype)
	{
		if (kyctype != null) {
			getMendixObject().setValue(context, MemberNames.kyctype.toString(), kyctype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.kyctype.toString(), null);
		}
	}

	/**
	 * @return value of mobilenumber
	 */
	public final java.lang.Long getmobilenumber()
	{
		return getmobilenumber(getContext());
	}

	/**
	 * @param context
	 * @return value of mobilenumber
	 */
	public final java.lang.Long getmobilenumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.mobilenumber.toString());
	}

	/**
	 * Set value of mobilenumber
	 * @param mobilenumber
	 */
	public final void setmobilenumber(java.lang.Long mobilenumber)
	{
		setmobilenumber(getContext(), mobilenumber);
	}

	/**
	 * Set value of mobilenumber
	 * @param context
	 * @param mobilenumber
	 */
	public final void setmobilenumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long mobilenumber)
	{
		getMendixObject().setValue(context, MemberNames.mobilenumber.toString(), mobilenumber);
	}

	/**
	 * Get value of mobiledeclaration
	 * @param mobiledeclaration
	 */
	public final myfirstmodule.proxies.emaildeclare getmobiledeclaration()
	{
		return getmobiledeclaration(getContext());
	}

	/**
	 * @param context
	 * @return value of mobiledeclaration
	 */
	public final myfirstmodule.proxies.emaildeclare getmobiledeclaration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.mobiledeclaration.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.emaildeclare.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of mobiledeclaration
	 * @param mobiledeclaration
	 */
	public final void setmobiledeclaration(myfirstmodule.proxies.emaildeclare mobiledeclaration)
	{
		setmobiledeclaration(getContext(), mobiledeclaration);
	}

	/**
	 * Set value of mobiledeclaration
	 * @param context
	 * @param mobiledeclaration
	 */
	public final void setmobiledeclaration(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.emaildeclare mobiledeclaration)
	{
		if (mobiledeclaration != null) {
			getMendixObject().setValue(context, MemberNames.mobiledeclaration.toString(), mobiledeclaration.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.mobiledeclaration.toString(), null);
		}
	}

	/**
	 * @return value of emailid
	 */
	public final java.lang.String getemailid()
	{
		return getemailid(getContext());
	}

	/**
	 * @param context
	 * @return value of emailid
	 */
	public final java.lang.String getemailid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.emailid.toString());
	}

	/**
	 * Set value of emailid
	 * @param emailid
	 */
	public final void setemailid(java.lang.String emailid)
	{
		setemailid(getContext(), emailid);
	}

	/**
	 * Set value of emailid
	 * @param context
	 * @param emailid
	 */
	public final void setemailid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailid)
	{
		getMendixObject().setValue(context, MemberNames.emailid.toString(), emailid);
	}

	/**
	 * Get value of emaildeclaration
	 * @param emaildeclaration
	 */
	public final myfirstmodule.proxies.emaildeclare getemaildeclaration()
	{
		return getemaildeclaration(getContext());
	}

	/**
	 * @param context
	 * @return value of emaildeclaration
	 */
	public final myfirstmodule.proxies.emaildeclare getemaildeclaration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.emaildeclaration.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.emaildeclare.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of emaildeclaration
	 * @param emaildeclaration
	 */
	public final void setemaildeclaration(myfirstmodule.proxies.emaildeclare emaildeclaration)
	{
		setemaildeclaration(getContext(), emaildeclaration);
	}

	/**
	 * Set value of emaildeclaration
	 * @param context
	 * @param emaildeclaration
	 */
	public final void setemaildeclaration(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.emaildeclare emaildeclaration)
	{
		if (emaildeclaration != null) {
			getMendixObject().setValue(context, MemberNames.emaildeclaration.toString(), emaildeclaration.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.emaildeclaration.toString(), null);
		}
	}

	/**
	 * Get value of pancategory
	 * @param pancategory
	 */
	public final myfirstmodule.proxies.pancategory getpancategory()
	{
		return getpancategory(getContext());
	}

	/**
	 * @param context
	 * @return value of pancategory
	 */
	public final myfirstmodule.proxies.pancategory getpancategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.pancategory.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.pancategory.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of pancategory
	 * @param pancategory
	 */
	public final void setpancategory(myfirstmodule.proxies.pancategory pancategory)
	{
		setpancategory(getContext(), pancategory);
	}

	/**
	 * Set value of pancategory
	 * @param context
	 * @param pancategory
	 */
	public final void setpancategory(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.pancategory pancategory)
	{
		if (pancategory != null) {
			getMendixObject().setValue(context, MemberNames.pancategory.toString(), pancategory.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.pancategory.toString(), null);
		}
	}

	/**
	 * @return value of middlename
	 */
	public final java.lang.String getmiddlename()
	{
		return getmiddlename(getContext());
	}

	/**
	 * @param context
	 * @return value of middlename
	 */
	public final java.lang.String getmiddlename(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.middlename.toString());
	}

	/**
	 * Set value of middlename
	 * @param middlename
	 */
	public final void setmiddlename(java.lang.String middlename)
	{
		setmiddlename(getContext(), middlename);
	}

	/**
	 * Set value of middlename
	 * @param context
	 * @param middlename
	 */
	public final void setmiddlename(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String middlename)
	{
		getMendixObject().setValue(context, MemberNames.middlename.toString(), middlename);
	}

	/**
	 * @return value of step2completed
	 */
	public final java.lang.Boolean getstep2completed()
	{
		return getstep2completed(getContext());
	}

	/**
	 * @param context
	 * @return value of step2completed
	 */
	public final java.lang.Boolean getstep2completed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.step2completed.toString());
	}

	/**
	 * Set value of step2completed
	 * @param step2completed
	 */
	public final void setstep2completed(java.lang.Boolean step2completed)
	{
		setstep2completed(getContext(), step2completed);
	}

	/**
	 * Set value of step2completed
	 * @param context
	 * @param step2completed
	 */
	public final void setstep2completed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean step2completed)
	{
		getMendixObject().setValue(context, MemberNames.step2completed.toString(), step2completed);
	}

	/**
	 * Get value of occuptation
	 * @param occuptation
	 */
	public final myfirstmodule.proxies.occupation getoccuptation()
	{
		return getoccuptation(getContext());
	}

	/**
	 * @param context
	 * @return value of occuptation
	 */
	public final myfirstmodule.proxies.occupation getoccuptation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.occuptation.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.occupation.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of occuptation
	 * @param occuptation
	 */
	public final void setoccuptation(myfirstmodule.proxies.occupation occuptation)
	{
		setoccuptation(getContext(), occuptation);
	}

	/**
	 * Set value of occuptation
	 * @param context
	 * @param occuptation
	 */
	public final void setoccuptation(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.occupation occuptation)
	{
		if (occuptation != null) {
			getMendixObject().setValue(context, MemberNames.occuptation.toString(), occuptation.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.occuptation.toString(), null);
		}
	}

	/**
	 * @return value of panexempt
	 */
	public final java.lang.Boolean getpanexempt()
	{
		return getpanexempt(getContext());
	}

	/**
	 * @param context
	 * @return value of panexempt
	 */
	public final java.lang.Boolean getpanexempt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.panexempt.toString());
	}

	/**
	 * Set value of panexempt
	 * @param panexempt
	 */
	public final void setpanexempt(java.lang.Boolean panexempt)
	{
		setpanexempt(getContext(), panexempt);
	}

	/**
	 * Set value of panexempt
	 * @param context
	 * @param panexempt
	 */
	public final void setpanexempt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean panexempt)
	{
		getMendixObject().setValue(context, MemberNames.panexempt.toString(), panexempt);
	}

	/**
	 * @return value of pkern
	 */
	public final java.lang.String getpkern()
	{
		return getpkern(getContext());
	}

	/**
	 * @param context
	 * @return value of pkern
	 */
	public final java.lang.String getpkern(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.pkern.toString());
	}

	/**
	 * Set value of pkern
	 * @param pkern
	 */
	public final void setpkern(java.lang.String pkern)
	{
		setpkern(getContext(), pkern);
	}

	/**
	 * Set value of pkern
	 * @param context
	 * @param pkern
	 */
	public final void setpkern(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pkern)
	{
		getMendixObject().setValue(context, MemberNames.pkern.toString(), pkern);
	}

	/**
	 * @return value of dataid
	 */
	public final java.lang.Integer getdataid()
	{
		return getdataid(getContext());
	}

	/**
	 * @param context
	 * @return value of dataid
	 */
	public final java.lang.Integer getdataid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.dataid.toString());
	}

	/**
	 * Set value of dataid
	 * @param dataid
	 */
	public final void setdataid(java.lang.Integer dataid)
	{
		setdataid(getContext(), dataid);
	}

	/**
	 * Set value of dataid
	 * @param context
	 * @param dataid
	 */
	public final void setdataid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer dataid)
	{
		getMendixObject().setValue(context, MemberNames.dataid.toString(), dataid);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return holderdetailsMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.holderdetails that = (myfirstmodule.proxies.holderdetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
