// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum iddoc
{
	pan(new java.lang.String[][] { new java.lang.String[] { "en_US", "PAN" }, new java.lang.String[] { "hi_IN", "PAN" } }),
	pasport(new java.lang.String[][] { new java.lang.String[] { "en_US", "pasport" } }),
	Election_ID_Card(new java.lang.String[][] { new java.lang.String[] { "en_US", "Election ID Card" } }),
	Driving_Licence(new java.lang.String[][] { new java.lang.String[] { "en_US", "Driving Licence" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private iddoc(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
