// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum incomeslab
{
	below1lakh(new java.lang.String[][] { new java.lang.String[] { "en_US", "below1lakh" }, new java.lang.String[] { "hi_IN", "1 लाख से नीचे" } }),
	_1to5lakh(new java.lang.String[][] { new java.lang.String[] { "en_US", "1to5lakh" } }),
	_5to10lakx(new java.lang.String[][] { new java.lang.String[] { "en_US", "5to10lakx" } }),
	_10_100lakh(new java.lang.String[][] { new java.lang.String[] { "en_US", "10-100lakh" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private incomeslab(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
