// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum occupation
{
	business(new java.lang.String[][] { new java.lang.String[] { "en_US", "business" }, new java.lang.String[] { "hi_IN", "व्यापार" } }),
	service(new java.lang.String[][] { new java.lang.String[] { "en_US", "service" }, new java.lang.String[] { "hi_IN", "सेवा" } }),
	agriculture(new java.lang.String[][] { new java.lang.String[] { "en_US", "agriculture" }, new java.lang.String[] { "hi_IN", "कृषि" } }),
	retired(new java.lang.String[][] { new java.lang.String[] { "en_US", "retired" }, new java.lang.String[] { "hi_IN", "सेवानिवृत्त" } }),
	housewife(new java.lang.String[][] { new java.lang.String[] { "en_US", "housewife" }, new java.lang.String[] { "hi_IN", "गृहिणी" } }),
	student(new java.lang.String[][] { new java.lang.String[] { "en_US", "student" }, new java.lang.String[] { "hi_IN", "छात्र" } }),
	others(new java.lang.String[][] { new java.lang.String[] { "en_US", "others" }, new java.lang.String[] { "hi_IN", "अन्य" } }),
	proffsional(new java.lang.String[][] { new java.lang.String[] { "en_US", "proffsional" }, new java.lang.String[] { "hi_IN", "पेशेवर" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private occupation(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
