// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum politicallyexposed
{
	yes(new java.lang.String[][] { new java.lang.String[] { "en_US", "yes" }, new java.lang.String[] { "hi_IN", "हाँ" } }),
	no(new java.lang.String[][] { new java.lang.String[] { "en_US", "no" }, new java.lang.String[] { "hi_IN", "नहीं" } }),
	notrelatedto_pep(new java.lang.String[][] { new java.lang.String[] { "en_US", "notrelatedto pep" }, new java.lang.String[] { "hi_IN", "PEP से संबंधित नहीं है" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private politicallyexposed(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
