// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum taxstatus
{
	AOP(new java.lang.String[][] { new java.lang.String[] { "en_US", "AOP" } }),
	Artificial_judiciary(new java.lang.String[][] { new java.lang.String[] { "en_US", "Artificial judiciary" } }),
	Bank_c0_operive_Bank(new java.lang.String[][] { new java.lang.String[] { "en_US", "Bank/co-operative Bank" } }),
	Body_corporate(new java.lang.String[][] { new java.lang.String[] { "en_US", "Body corporate" } }),
	body_of_individual(new java.lang.String[][] { new java.lang.String[] { "en_US", "body of individual" } }),
	company(new java.lang.String[][] { new java.lang.String[] { "en_US", "company" } }),
	DFI(new java.lang.String[][] { new java.lang.String[] { "en_US", "DFI" } }),
	FII(new java.lang.String[][] { new java.lang.String[] { "en_US", "FII" } }),
	FCRA(new java.lang.String[][] { new java.lang.String[] { "en_US", "FCRA" } }),
	Government_Body(new java.lang.String[][] { new java.lang.String[] { "en_US", "Government Body" } }),
	HUF(new java.lang.String[][] { new java.lang.String[] { "en_US", "HUF" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private taxstatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
