// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.regex.Pattern;

public class Java_Valid_Email extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String email;

	public Java_Valid_Email(
		IContext context,
		java.lang.String _email
	)
	{
		super(context);
		this.email = _email;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        // Define the email regex pattern
        String emailPattern = "^[\\w.%+-]+@[\\w.-]+\\.[a-zA-Z]{2,6}$";

        // Validate the email using regex
        if (this.email == null || this.email.isEmpty()) {
            return false; // Invalid if email is null or empty
        }

        return Pattern.matches(emailPattern, this.email);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_Valid_Email";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
