// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Java_ValidMoblNo extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.Long MobileNo;

	public Java_ValidMoblNo(
		IContext context,
		java.lang.Long _mobileNo
	)
	{
		super(context);
		this.MobileNo = _mobileNo;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        // Convert the MobileNo to a string
        String mobileNoStr = this.MobileNo != null ? this.MobileNo.toString() : null;

        // Check if the input is null or empty
        if (mobileNoStr == null || mobileNoStr.isEmpty()) {
            return false; // Invalid if null or empty
        }

        // Ensure the number has exactly 10 digits
        if (!mobileNoStr.matches("\\d{10}")) {
            return false; // Invalid if not 10 digits
        }

 // Check if the first digit is either 8 or 9
        char firstDigit = mobileNoStr.charAt(0);
        if (firstDigit != '8' && firstDigit != '9' && firstDigit != '7') {
            return false; // Invalid if the first digit is not 8 or 9
        }

        // Check if all digits are between 1 and 9
        for (char digit : mobileNoStr.toCharArray()) {
            if (digit < '0' || digit > '9') {
                return false; // Invalid if any digit is 0
            }
        }

        return true; // Valid mobile number
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_ValidMoblNo";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
