// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.regex.Pattern;

public class Java_ValidPKERN extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String PKERN;

	public Java_ValidPKERN(
		IContext context,
		java.lang.String _pKERN
	)
	{
		super(context);
		this.PKERN = _pKERN;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        // Define the PAN regex pattern for Indian PAN validation
        String panPattern = "^[A-Z]{5}[0-9]{4}[A-Z]$";

        // Validate the PAN using regex
        if (this.PKERN == null || this.PKERN.isEmpty()) {
            return false; // Invalid if PAN is null or empty
        }

        return Pattern.matches(panPattern, this.PKERN);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_ValidPKERN";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
