// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Java_ValidAccntNo extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String accntno;

	public Java_ValidAccntNo(
		IContext context,
		java.lang.String _accntno
	)
	{
		super(context);
		this.accntno = _accntno;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        // Check if account number is null or empty
        if (this.accntno == null || this.accntno.isEmpty()) {
            return false; // Invalid if null or empty
        }

        // Check if the account number is numeric
        if (!this.accntno.matches("\\d+")) {
            return false; // Invalid if not numeric
        }

        // Check if the account number length is between 10 and 15 digits
        if (this.accntno.length() < 10 || this.accntno.length() > 15) {
            return false; // Invalid if length is not between 10 and 15 digits
        }

        // Account number is valid if all checks pass
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_ValidAccntNo";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
