// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.util.Date;

public class Java_Validdateinfuture extends CustomJavaAction<java.lang.Boolean>
{
	private final java.util.Date date;

	public Java_Validdateinfuture(
		IContext context,
		java.util.Date _date
	)
	{
		super(context);
		this.date = _date;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        if (this.date == null) {
            return false; // Invalid if date is null
        }

        // Get the current system date
        Date currentDate = new Date();

        // Compare the given date with the current date
        if (this.date.after(currentDate)) {
            return false; // Invalid if the date is in the future
        }

        return true; // Valid if the date is not in the future
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_Validdateinfuture";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
