// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Java_validIFSC extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String IFSC;

	public Java_validIFSC(
		IContext context,
		java.lang.String _iFSC
	)
	{
		super(context);
		this.IFSC = _iFSC;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        // Check if IFSC is null or empty
        if (this.IFSC == null || this.IFSC.isEmpty()) {
            return false; // Invalid if null or empty
        }

        // Check if IFSC is exactly 11 characters long
        if (this.IFSC.length() != 11) {
            return false; // Invalid if length is not 11
        }

        // Check if the first 4 characters are letters, the fifth is '0', and the last 6 characters are digits
        if (!this.IFSC.matches("[A-Za-z]{4}0\\d{6}")) {
            return false; // Invalid if format does not match <4 letters>0<6 digits>
        }



        // If all checks pass, the IFSC code is valid
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_validIFSC";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
